### ISSUE TITLE
Don't include .git in published package

### ISSUE THREAD

**Issue by mogelbrod** [cvpcasada/use-measure#1]
The `.git` directory is included in the published package (see https://unpkg.com/use-measure@0.2.0/), preventing `npm install` from working:
```
npm ERR! path .../package/node_modules/use-measure
npm ERR! code EISGIT
npm ERR! git .../package/node_modules/use-measure: Appears to be a git repo or submodule.
npm ERR! git     .../package/node_modules/use-measure
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by cvpcasada** [comment]
whoa, thats weird... npm's doc https://docs.npmjs.com/files/package.json#files says they're always ignored.. Anyways the fault is in the package.json `files` field. I've Fixed it now as 0.2.1 release.

Thanks for submitting the issue :)
