### ISSUE TITLE
Missing use-measure.d.ts typings 

### ISSUE THREAD

**Issue by FinestV** [cvpcasada/use-measure#2]
Version 0.2.1 does not contain the `use-measure.d.ts` file when installed. As a consumer i need to declare the use-measure module in my own `.d.ts`

![image](https://user-images.githubusercontent.com/13340489/56874575-de5c4500-6a8e-11e9-9f73-1cd0f7fe936e.png)

Can the next version please be published with the `use-measure.d.ts` included? I see you are already generating it as part of the build task.

**Comment by cvpcasada** [comment]
done.. fix at v0.2.2
