### ISSUE TITLE
Equals x-value for all items

### ISSUE THREAD

**Issue by eseQ** [cvpcasada/use-measure#7]
Hello.
Here (https://github.com/souporserious/react-measure/issues/141#issuecomment-559360342) I describe my case and find strange behavior in `use-measure`.

**Comment by cvpcasada** [comment]
Hi @eseQ , sorry for late response. This library returns ResizeObserver's contentRect (see https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry) you may use https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect instead

```js
function useClientRectMeasure(nodeRef) {
  const [clientRect, setClientRect] = useState({});
  const contentRect = useMeasure(nodeRef);

  // set clientRect value when contentRect updates
  useEffect(() => {
    setClientRect(nodeRef.current.getBoundingClientRect());
  }, [contentRect, setClientRect])

  return clientRect;
}
```

**Comment by eseQ** [comment]
@cvpcasada Thanks for your answer. But
Every time except did mount `contentRect` will be ignored and not trigger useEffect. Each param in `contentRect` will be the same to item (`x` will be equal for all items). Nothing changes when a new item will be added.

**Comment by eseQ** [comment]
Reproduce https://codesandbox.io/s/modest-list-56t7e. `useEffect` will be triggered only on the new item.
